Complete refactor of codebase

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,57 +1,110 @@
 #!/bin/sh
 
-sudo apk update
-sudo apk upgrade
+# Exit on any error
+set -e
 
-DIR="$(dirname "$(realpath "$0")")"
-DOT=$DIR/dotfiles
+# Check if sudo is available
+command -v sudo > /dev/null 2>&1 || { echo >&2 "The script requires 'sudo' but it's not installed.  Aborting."; exit 1; }
 
-# Install base packages
-sudo apk add build-base cmake openssl-dev pulseaudio python3 xcb-util-dev xcb-util-renderutil-dev xcb-util-image-dev tar udev dbus seatd cmd:seatd-launch fontconfig-dev curl wget
+# Update and upgrade packages
+sudo apk update && sudo apk upgrade
 
-# Install drivers
-sudo apk add mkinitfs linux-firmware-amdgpu mesa mesa-dri-gallium mesa-va-gallium
-sudo echo amdgpu >> /etc/modules
-sudo echo fbcon >> /etc/modules
+# Function to add a user to groups if not already added
+add_user_to_group() {
+    for group in "$@"; do
+        if ! id -nGz "$USER" | grep -qzxF "$group"; then
+            sudo adduser $USER $group
+        fi
+    done
+}
 
-# Install wayland
-sudo apk add wayland xwayland wl-clipboard
+# Install packages
+install_packages() {
+    for pkg in "$@"; do
+        if ! apk info -e "$pkg" >/dev/null 2>&1; then
+            sudo apk add $pkg
+        fi
+    done
+}
 
-# Install sway
-sudo apk add sway swaylock swaybg swayidle
+# Install Development Essentials
+install_packages \
+    build-base \
+    cmake \
+    openssl-dev \
+    python3 \
+    curl \
+    wget \
+    tar \
+    git \
+    fontconfig-dev
 
-# Install user packages
-sudo apk add docker docker-cli-compose firefox-developer-edition neovim font-jetbrains-mono-nerd alacritty tmux rustup nodejs yarn npm lua-language-server stylua
+# Install XCB-related packages
+install_packages \
+    xcb-util-dev \
+    xcb-util-renderutil-dev \
+    xcb-util-image-dev
+
+# Install Audio/Video related packages
+install_packages \
+    pulseaudio \
+    linux-firmware-amdgpu \
+    mesa \
+    mesa-dri-gallium \
+    mesa-va-gallium
+
+# Install Wayland/Sway related packages
+install_packages \
+    wayland \
+    xwayland \
+    wl-clipboard \
+    sway \
+    swaylock \
+    swaybg \
+    swayidle \
+    udev \
+    dbus \
+    seatd \
+    cmd:seatd-launch
+
+# Install Developer tools
+install_packages \
+    neovim \
+    ripgrep \
+    mprocs \
+    rustup \
+    nodejs \
+    yarn \
+    npm \
+    lua-language-server \
+    stylua \
+    docker \
+    docker-cli-compose
+
+# Install Applications
+install_packages \
+    firefox-developer-edition \
+    ncspot \
+    alacritty \
+    tmux \
+    font-jetbrains-mono-nerd
 
 # Install node packages
 yarn global add typescript typescript-language-server
 
-# Install neovim
-mkdir -p ~/.config
-git clone https://github.com/NvChad/NvChad.git --depth 1 ~/.config/nvim
-
 # Setup services
+echo amdgpu | sudo tee -a /etc/modules
+echo fbcon | sudo tee -a /etc/modules
 sudo setup-devd udev
 echo $(sudo dbus-uuidgen) | sudo tee /var/lib/dbus/machine-id >/dev/null
 sudo rc-update add dbus
 sudo rc-update add seatd default
 
 # Add user to groups
-for group in input video seat; do sudo adduser $USER $group; done
+add_user_to_group input video seat
 
 # Setup rust
 rustup-init -y --default-toolchain nightly
-source "$DOT/.profile"
 
 # Install cargo binaries
-cargo install cargo-binstall
-cargo binstall cargo-generate cargo-leptos ncspot ripgrep kickoff --locked
-
-# Link dotfiles
-./lnx $DOT/sway ~/.config/sway
-./lnx $DOT/alacritty ~/.config/alacritty
-./lnx $DOT/nvim ~/.config/nvim
-./lnx $DOT/ncspot ~/.config/ncspot
-ln -sf $DOT/.tmux.conf ~/.tmux.conf
-ln -sf $DOT/.gitconfig ~/.gitconfig
-ln -sf $DOT/.profile ~/.profile
+cargo install kickoff --locked
